# Dockerfile for the scheduler image

FROM rocker/tidyverse:3.5.1

RUN R -e 'devtools::install_github("Azure/rAzureBatch", \
  ref = "6ca2bf7b1f4433a27531eaa86f0317499e9b4987")'

RUN R -e 'devtools::install_github("Azure/doAzureParallel", \
  ref = "975858072e8194d465a1f63262e35815ebbf0306")'
  
RUN install2.r --error --repos https://mran.microsoft.com/snapshot/2019-05-20 \
  dotenv \
  jsonlite \
  AzureStor

WORKDIR /job
ADD R /job/R
ADD 03_forecast_on_batch.R /job/03_forecast_on_batch.R
RUN mkdir /job/azure

CMD ["Rscript", "03_forecast_on_batch.R"]